MyAuditApplication/Entities/Object.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAuditApplication
{
    public class Object
    {
        public string Id { get; set; }
        public double Timestamp { get; set; }
        public string Type { get; set; }
        public string Changes { get; set; }
    }
}

MyAuditApplication/Entities/Result.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAuditApplication.Entities
{
    public enum ResultCode { Success=1,Error=0, NoRecordFound=2};
    public class Result
    {
        public ResultCode Code { get; set; }
        public string Message { get; set; }
    }
}

MyAuditApplication/Models/ObjectState.cs
using MyAuditApplication.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyAuditApplication.Models
{
    public class ObjectState:Result
    {
        public string state;
    }
}

MyAuditApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyAuditApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MyAuditApplication/Controllers/ObjectController.cs
using MyAuditApplication.BusinessLayer;
using MyAuditApplication.Models;
using MyAuditApplication.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyAuditApplication.Controllers
{
    public class ObjectController : Controller
    {
        // GET: FileUpload
        public ActionResult Upload()
        {          
            return View();
        }
        [HttpPost]
        public ActionResult ProcessCSV()
        {
            if (Request.Files.Count == 1)
            {
                var postedFile = Request.Files[0];
                if (postedFile.ContentLength > 0)
                {
                    List<Object> objects = new List<Object>();
                    using (var csvReader = new System.IO.StreamReader(postedFile.InputStream))
                    {
                        try
                        {
                            string inputLine = "";
                            csvReader.ReadLine();
                            while ((inputLine = csvReader.ReadLine()) != null)
                            {
                                string[] inputValues = inputLine.Split(new char[] { ',' });
                                Object obj = new Object()
                                {
                                    Id = inputValues[0],
                                    Type = inputValues[1],
                                    Timestamp = Convert.ToDouble(inputValues[2]),
                                    Changes = inputLine.Substring(inputLine.IndexOf(inputValues[3]))
                                };
                                objects.Add(obj);
                            }
                            csvReader.Close();
                        }
                        catch(Exception ex)
                        {
                            ViewBag.ErrorClass = Constants.CssErrorClass;
                            ViewBag.ErrorMessage = "Error: " + ex.Message;
                            return View("Upload", "_Layout", ViewBag.ErrorMessage);
                        }
                    }

                    ObjectBL.SaveObjects(objects);

                }
            }
            return Redirect("../");
        }

        //Get Search 
        public ActionResult Search()
        {
            return View();
        }

        [HttpPost]
        public string RetrieveObjectState(FormCollection form)
        {
            ObjectState objectState = null;
            try
            {
                 objectState = ObjectBL.FindObjectState(form["objectType"].ToString(), form["objectId"].ToString(), Convert.ToDouble(form["objectTimestamp"].ToString()));
                if (objectState.Code == Entities.ResultCode.NoRecordFound)
                    objectState.state = "#Object didn't exist at that time";
            }
            catch(Exception ex)
            {
                ViewBag.ErrorClass = Constants.CssErrorClass;
                ViewBag.ErrorMessage = "Error: " + ex.Message; 
                return View("Search", "_Layout", ViewBag.ErrorMessage);
            }
            return objectState.state.ToString(); 
        }
    }
}

MyAuditApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyAuditApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyAuditApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MyAuditApplication/Views/Object/Search.cshtml
@section scripts{
<script type="text/javascript">
    $('document').ready(function () {
        $('#btnSearch').click(function () {
            $.post("RetrieveObjectState", $("form").serialize(), function (data) {
                $(".result").html(data);
            });
            return false;
        }
        );
    });
</script>
}
@{
    ViewBag.Title = "Search";
}

<h2>Search for Object state</h2>
<div class="@ViewBag.ErrorClass">
    <span>
        @ViewBag.ErrorMessage
    </span>
</div>
@using (Html.BeginForm("RetrieveObjectState", "Object", FormMethod.Post))
{
    <div class="question">
        <div class="editor-label">
            Object Type :
        </div>
        <div class="editor-field">
            <input type="text" name="objectType" id="objectType" value="" />
        </div>
    </div>
    <div class="question">
        <div class="editor-label">
            Object Id :
        </div>
        <div class="editor-field">
            <input type="text" name="objectId" id="objectId" value="" />
        </div>
    </div>
    <div class="question">
        <div class="editor-label">
            Timestamp :
        </div>
        <div class="editor-field">
            <input type="text" name="objectTimestamp" id="objectTimestamp" value="" />
        </div>
    </div>
    <div style="padding:10px 18%;">
        <input id="btnSearch" type="submit" value="Search" />
    </div>

    <div class="result">

    </div>

}

MyAuditApplication/Views/Object/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}
<h2>Upload CSV Files</h2>

<div class="@ViewBag.ErrorClass">
    <span>
        @ViewBag.ErrorMessage
    </span>
</div>

@using (Html.BeginForm("ProcessCSV", "Object", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input name="files" type="file" accept="csv" data-val="true" data-val-required="File is required" />
    <input type="submit" style="padding: 0px 20px;margin: 20px 0px;" value="Upload" />
}

MyAuditApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TG Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Upload", "Upload", "Object")</li>
                    <li>@Html.ActionLink("Search", "Search", "Object")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <footer>
            <p>&copy; @DateTime.Now.Year - TG Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>